#!/bin/bash

syntax()
{
echo "usage: makerepo [repolist.file] [repo/directory]"
exit 0
}

test "$1" != "-h" || syntax
test "$1" != "--help" || syntax
test "$1" != "help" || syntax


error()
{
if [ "$?" != "0" ]; then
status=Failed
cd ..
exit 1
fi
}

test -n $1 || $(echo "Specify repolist file" && exit &>2)
test -n $2 || $(echo "Specify repo directory" && exit &>2)
if [ -d $2 ]; then
	rm -r $2
	mkdir -p $2
else
mkdir -p $2
fi

packlist=$(pwd)/$1
cd $2

for i in $(cat $packlist); do
error
yaourt -Gf --noconfirm $i
cd $i
error
makepkg -sc --noconfirm
error
cd ..
cp -f $i/*pkg.tar.xz ./
rm -r $i
done
repo-add flux.db.tar.gz *.tar.xz
